### ISSUE TITLE
BUG: dead-hosts keeps pulling configuration error Action

### ISSUE THREAD

**Issue by bigdargon** [funilrys/PyFunceble#314]
## Description

The configuration file in the editing library adds new lines, causing the Action to fail

https://github.com/dead-hosts/template/commit/6d7abb0b31648cb33d3673c35b87a6bdae2b4f94

```
https: null
    rules: []
share_logs: false
user_agent:
    browser: chrome
    custom: null
    platform: linux
verify_ssl_certificate: false
```

In the previous comment I mentioned https://github.com/funilrys/PyFunceble/issues/299#issuecomment-1196221039, but after fixing, only 1 line A was removed, the remaining lines were still added.

I think, dead-hosts after running the Action pulled themselves PyFunceble's default configuration to override the dead-hosts' Action. But for some reason, the default configuration end was appended with malformed configuration lines, causing the Action to fail.

Thanks again for your project!

**Comment by funilrys** [comment]
https://github.com/funilrys/PyFunceble/commit/fe717b2d6404516353d2cccf4c5943bc7c9e39a6 touches this issue.

**Comment by funilrys** [comment]
@bigdargon I deployed a new version of the `dead-hosts-launcher` package with a few fixes. Please try it and let me know.

**Comment by funilrys** [comment]
@bigdargon https://github.com/funilrys/PyFunceble/commit/8c74cafc060f13c6ff3858d7da026d74ece852fc should fix this. 

Please be patient this issue will be closed automatically, once the commit lands in the `dev` branch.

**Comment by bigdargon** [comment]
@funilrys Looks like the error is still there https://github.com/bigdargon/hostsVN-dead-hosts/commit/12cbfa0a4c40f8a33a91f1e776478d9d7eea78e6
