### ISSUE TITLE
-dns switch to use custom dns server is not working in Windows, still uses OS settings

### ISSUE THREAD

**Issue by opav** [funilrys/PyFunceble#45]
Tested on - pyfunceble 2.6.6.dev (Green Galago: Skitterbug) with Python 3.7.4 (Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32)

-dns switch to use custom dns server is not working in Windows 7, still uses OS settings for DNS.

I also tried setting in .PyFunceble.yaml but it still goes to OS defined DNS server.

Is this a PyFunceble or Python issue?

**Comment by funilrys** [comment]
Hi @opav,

Sorry for the delay, I got to setup Windows 10 so that I can develop and try to debug from there.

May I ask how do determine that PyFunceble still uses the OS settings ?

Also, thanks for using the dev branch! Feedback from the dev branch helps a lot!

Today (Berlin Time) I made a push to the dev, it includes the logger.
Can you update to the latest version and give me the content of `output/logs/debug.log` after running the following ?  
**WARNING if you don't want to expose your DNS IP/Server Name, please anonymize or send the log privately per email or [KeyBase](https://keybase.io/funilrys) (prefered). All issue/debug data shared privately with me will be safely destroyed from my machine and Keybase once the issue is resolved.**

```powershell
> PyFunceble -d google.com --debug --no-whois --dns yourDNSServer 
```

Thanks again for your feedback.

Cheers,
Nissar

**Comment by funilrys** [comment]
Hi @opav,

Can you test if the patch I just pushed fixes your issue? 

Cheers,
Nissar

**Comment by opav** [comment]
Sorry was away, will test it shortly.

**Comment by opav** [comment]
Hi @funilrys ,

I install a fresh pyfunceble 2.11.6.dev (Green Galago: Skitterbug) with all defaults and the problem still persist.

I can confirm it is still using my OS DNS (which points to a DNS server on my network), from the queries in my DNS server log.

[debug.log](https://github.com/funilrys/PyFunceble/files/3666074/debug.log)

Hope the log helps, thank you.

**Comment by mitchellkrogza** [comment]
Tested on Windows 10
PyFunceble 2.13.0.dev

Does indeed use the external DNS server I specified

![2019-10-01_14-04](https://user-images.githubusercontent.com/9961541/65960290-769e9180-e454-11e9-8860-1493799d1f67.png)

![2019-10-01_14-07](https://user-images.githubusercontent.com/9961541/65960365-9afa6e00-e454-11e9-9df1-1959513bc109.png)

**Comment by opav** [comment]
I am on Windows 7 and I noticed the Python version is a bit different from @mitchellkrogza , mine says:

**Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]**

**Comment by opav** [comment]
So I just installed latest PyF-dev and this time x64 Python but it is still going to my DNS instead of 8.8.8.8:

**pyfunceble 2.13.0.dev (Green Galago: Skitterbug)**
**Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]**

![image](https://user-images.githubusercontent.com/6770347/65973705-5c89a100-e49e-11e9-9469-0b6fe09eaf8f.png)

![image](https://user-images.githubusercontent.com/6770347/65973735-67443600-e49e-11e9-9fa2-2df2a97d573f.png)

**Comment by funilrys** [comment]
I came to the same conclusion as @mitchellkrogza .... But we are using Windows 10 :disappointed: 

Can you test the following locally and tell me if there is a difference (from the DNS log)

```python
import dns.resolver

# This is the part we do.
# We don't touch the default resolver, we use a new one.
our_resolver = dns.resolver.Resolver(configure=False)
our_resolver.nameservers = ["8.8.8.8"]

print(our_resolver.query('google.com', 'A').response)

print("*" * 50)

# This is the part we don't do and the possible solution for your case.
# We replace the default resolver. and work with it.
dns.resolver.default_resolver = dns.resolver.Resolver(configure=False)
dns.resolver.default_resolver.nameservers = ['8.8.8.8']

print(dns.resolver.query('google.org', 'A').response)
```

Cheers,
Nissar

**Comment by opav** [comment]
That snippet works!  

It went directly to 8.8.8.8.  Confirmed my DNS log has no queries.  And also saw the outbound packets going to 8.8.8.8 from my router's tcpdump trace.

**Comment by mitchellkrogza** [comment]
Do you have any DNS servers hard coded in your network settings? With windows that could well be a cause of what you experienced.
 
![2019-10-02_08-34](https://user-images.githubusercontent.com/9961541/66022801-5e2f8500-e4ef-11e9-9b66-8d7c8a974785.png)

**Comment by funilrys** [comment]
@opav which one worked? `google.com` org `google.org` ?

**Comment by opav** [comment]
Both queries works.  Meaning both went direct to 8.8.8.8.

Think we are getting close to the issue.



```Z:\PyFunceble-dev>testdns.py                      
id 44003                                          
opcode QUERY                                      
rcode NOERROR                                     
flags QR RD RA                                    
;QUESTION                                         
google.com. IN A                                  
;ANSWER                                           
google.com. 142 IN A 172.217.194.113              
google.com. 142 IN A 172.217.194.138              
google.com. 142 IN A 172.217.194.139              
google.com. 142 IN A 172.217.194.100              
google.com. 142 IN A 172.217.194.101              
google.com. 142 IN A 172.217.194.102              
;AUTHORITY                                        
;ADDITIONAL                                       
**************************************************
id 27511                                          
opcode QUERY                                      
rcode NOERROR                                     
flags QR RD RA                                    
;QUESTION                                         
google.org. IN A                                  
;ANSWER                                           
google.org. 300 IN A 216.239.32.27                
;AUTHORITY                                        
;ADDITIONAL 
```

**Comment by funilrys** [comment]
@opav What if you run ?
```
PyFunceble -d github.com --http --dns yourDNSServer
```

**Comment by opav** [comment]
This works as expected, went to 8.8.8.8 as specified - 
`PyFunceble -d github.com --http --dns 8.8.8.8 --no-whois`

.....

I also trace thru dns_lookup.py and it seems for the earlier commands, the code is getting results from this, the default OS resolver, instead of my specified __--dns_ server_?

https://github.com/funilrys/PyFunceble/blob/02032fca6872734e220339841f012d6221b8c7c3/PyFunceble/dns_lookup.py#L350

**Comment by funilrys** [comment]
Nope, our issue is actually coming from :

https://github.com/funilrys/PyFunceble/blob/02032fca6872734e220339841f012d6221b8c7c3/PyFunceble/http_code.py#L151-L166

The patch is written but I'm doing some review of the patch itself in order to avoid a big performance loss.

**Comment by funilrys** [comment]
@opav As the new version was released by the CI tool, can you test and tell us ? https://pypi.org/project/PyFunceble-dev/#files

**P.S: Please DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/5398233e149b93c34343a387bfffeab68294c069 will be merged to master.**
